/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_handworks_CameraPreview */

#ifndef _Included_com_android_handworks_CameraPreview
#define _Included_com_android_handworks_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_handworks_CameraPreview
 * Method:    Handworks
 * Signature: (II[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_handworks_CameraPreview_Handworks
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
